In [1]:
import numpy as np

In [2]:
b = np.arange(24).reshape(2, 3, 4)

In [3]:
b.shape

(2, 3, 4)

In [4]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
b[0, 0, 0]

0

In [6]:
b[:, 0, 0]

array([ 0, 12])

In [7]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b[0,::]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
b[0, 1]

array([4, 5, 6, 7])

In [11]:
b[0, 1,::2]

array([4, 6])

In [12]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [13]:
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [14]:
b[0,:,-1]

array([ 3,  7, 11])

In [15]:
b[0,::-1,-1]

array([11,  7,  3])

In [16]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [17]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
b.ravel

<function ndarray.ravel>

In [19]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
b.shape = (6, 4)

In [22]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [24]:
b.resize((2, 12))

In [25]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [26]:
a = np.arange(9).reshape(3, 3)

In [27]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
b = a * 2

In [29]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [30]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [31]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [32]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [33]:
np.concatenate((a, b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [34]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [35]:
oned = np.arange(2)

In [36]:
oned

array([0, 1])

In [37]:
twice_oned = oned * 2
twice_oned

array([0, 2])

In [38]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [39]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [40]:
np.hstack((a, b)) == np.column_stack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

In [41]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [42]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [43]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [44]:
np.row_stack((a, b)) == np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [45]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [47]:
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [48]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [49]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [50]:
c = np.arange(27).reshape(3, 3, 3)

In [51]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [53]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [54]:
b.ndim

2

In [55]:
b.size

9

In [56]:
b.itemsize

8

In [57]:
b.nbytes

72

In [58]:
b.size * b.itemsize

72

In [59]:
b.T

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [60]:
b = np.array([1.j + 2, 3.j + 4.5])

In [61]:
b

array([ 2.0+1.j,  4.5+3.j])

In [62]:
b.real

array([ 2. ,  4.5])

In [63]:
b.imag

array([ 1.,  3.])

In [64]:
b.dtype

dtype('complex128')

In [65]:
b = np.arange(4).reshape(2, 2)

In [66]:
b

array([[0, 1],
       [2, 3]])

In [67]:
f = b.flat

In [68]:
f

In [69]:
for item in f: print(item)

0
1
2
3


In [70]:
b.flat[3]

3

In [71]:
b.flat[1]

1

In [72]:
b.flat[[1, 3]]

array([1, 3])

In [73]:
b.flat = 8

In [74]:
b

array([[8, 8],
       [8, 8]])

In [75]:
b.flat[[1, 3]] = 6

In [76]:
b

array([[8, 6],
       [8, 6]])

In [77]:
b.tolist()

[[8, 6], [8, 6]]

In [78]:
i2 = np.eye(2)

In [79]:
i2

array([[ 1.,  0.],
       [ 0.,  1.]])

In [80]:
np.savetxt("eye.txt", i2)